version: "3.7"

services:
  blog:
    image: webdevops/php-nginx:7.3 
    restart: always
    volumes:
      - ./web:/app
      - ./config/vhost.conf:/opt/docker/etc/nginx/vhost.conf
    env_file:
      - ./config/php.env
    labels:
      - 'traefik.frontend.rule=Host:site.stationpro.ml'
      - "traefik.docker.network=traefik_default"
      - 'traefik.port=80'
    networks:
      - web

volumes:
    db-data:
networks:
  web:
    external:
      name: traefik_default

